name: Opdex-Node
trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  ARTIFACT_NAME: 'opdex-node'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: Build
    displayName: Build and Publish

    variables:
      SOLUTION: 'OpdexFullNode.sln'
      BUILD_CONFIGURATION: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: $(SOLUTION)
      displayName: Restore

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: $(SOLUTION)
        arguments: '--configuration $(BUILD_CONFIGURATION) --no-restore'
      displayName: 'Build'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: $(SOLUTION)
        publishWebProjects: False
        arguments: '--configuration $(BUILD_CONFIGURATION) --no-build --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: False
      displayName: Publish

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/src/Opdex.Cirrus/Dockerfile'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Dockerfile'
        overwrite: True
      displayName: Copy Dockerfile

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(ARTIFACT_NAME)'
      displayName: Share

  - job: Push
    displayName: Docker Build and Push

    variables:
      IMAGE_REPOSITORY: 'opdex-node'
      DOCKERFILE_PATH: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME)/Dockerfile'
      TAG: '$(Build.BuildId)'

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'acradam'
        repository: '$(IMAGE_REPOSITORY)'
        command: 'buildAndPush'
        Dockerfile: '$(DOCKERFILE_PATH)'
        tags: '$(TAG)'
