name: Opdex-Node
trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ca5a974e-7f9c-44bc-ac22-3526d4b09fe8'
  imageRepository: 'opdex-node'
  containerRegistry: 'acradam.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Opdex.Cirrus/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: Build
    displayName: Build and Push
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
